server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

spring:
  cloud:
    gateway:
      routes:
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/api/msg/**
        - id: kafka-service
          uri: lb://kafka-service
          predicates:
            - Path=/api/kafka/**